name: presubmit
on: [pull_request, workflow_call, workflow_dispatch]

jobs:
  test:
    name: cargo test --all-features
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: moonrepo/setup-rust@d8048d4fdff0633123678b093726e6d7c8ad6de5
        with:
          inherit-toolchain: true
      - run: cargo test --all-features

  rustfmt:
    name: cargo +nightly fmt -- --check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: moonrepo/setup-rust@d8048d4fdff0633123678b093726e6d7c8ad6de5
        with:
          components: rustfmt
          channel: nightly
      - run: cargo +nightly fmt -- --check

  cranky:
    name: cargo +nightly cranky --all-targets -- -D warnings
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: moonrepo/setup-rust@d8048d4fdff0633123678b093726e6d7c8ad6de5
        with:
          components: clippy
          bins: cargo-cranky@0.3.0
          channel: nightly
      - run: cargo +nightly cranky --all-targets -- -D warnings

  deny:
    name: cargo deny --all-features check licenses
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install Rust toolchain
        uses: moonrepo/setup-rust@d8048d4fdff0633123678b093726e6d7c8ad6de5
        with:
          inherit-toolchain: true
          bins: cargo-deny
      - run: cargo deny --all-features check licenses
