name: presubmit
on: [pull_request, workflow_call, workflow_dispatch]

jobs:
  test:
    name: cargo test --all-features
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670
        with:
          inherit-toolchain: true
      - run: cargo test --all-features

  rustfmt:
    name: cargo +nightly fmt -- --check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670
        with:
          components: rustfmt
          channel: nightly
      - run: cargo +nightly fmt -- --check

  cranky:
    name: cargo +nightly cranky --all-targets -- -D warnings
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670
        with:
          components: clippy
          bins: cargo-cranky@0.3.0
          channel: nightly
      - run: cargo +nightly cranky --all-targets -- -D warnings

  deny:
    name: cargo deny --all-features check licenses
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Rust toolchain
        uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670
        with:
          inherit-toolchain: true
          bins: cargo-deny
      - run: cargo deny --all-features check licenses
