name: presubmit
on: [pull_request, workflow_call, workflow_dispatch]

jobs:
  test:
    name: cargo test --all-features
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3
        with:
          inherit-toolchain: true
      - run: cargo test --all-features

  rustfmt:
    name: cargo +nightly fmt -- --check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3
        with:
          components: rustfmt
          channel: nightly
      - run: cargo +nightly fmt -- --check

  cranky:
    name: cargo +nightly cranky --all-targets -- -D warnings
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3
        with:
          components: clippy
          bins: cargo-cranky@0.3.0
          channel: nightly
      - run: cargo +nightly cranky --all-targets -- -D warnings

  deny:
    name: cargo deny --all-features check licenses
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Install Rust toolchain
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3
        with:
          inherit-toolchain: true
          bins: cargo-deny
      - run: cargo deny --all-features check licenses
