name: presubmit
on: [pull_request, workflow_call, workflow_dispatch]

jobs:
  test:
    name: cargo test --all-features
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - uses: moonrepo/setup-rust@e013866c4215f77c925f42f60257dec7dd18836e
        with:
          inherit-toolchain: true
      - run: cargo test --all-features

  rustfmt:
    name: cargo +nightly fmt -- --check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - uses: moonrepo/setup-rust@e013866c4215f77c925f42f60257dec7dd18836e
        with:
          components: rustfmt
          channel: nightly
      - run: cargo +nightly fmt -- --check

  cranky:
    name: cargo +nightly cranky --all-targets -- -D warnings
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - uses: moonrepo/setup-rust@e013866c4215f77c925f42f60257dec7dd18836e
        with:
          components: clippy
          bins: cargo-cranky@0.3.0
          channel: nightly
      - run: cargo +nightly cranky --all-targets -- -D warnings

  deny:
    name: cargo deny --all-features check licenses
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - name: Install Rust toolchain
        uses: moonrepo/setup-rust@e013866c4215f77c925f42f60257dec7dd18836e
        with:
          inherit-toolchain: true
          bins: cargo-deny
      - run: cargo deny --all-features check licenses
